packages:
  - workflow
  - model
  - ui
  - block
  - test

catalog:
  '@platforma-sdk/workflow-tengo': ^2.15.4
  '@platforma-sdk/model': ^1.22.59
  '@platforma-sdk/ui-vue': ^1.22.82
  '@platforma-sdk/tengo-builder': ^1.19.2
  '@platforma-sdk/block-tools': ^2.5.18
  '@platforma-sdk/eslint-config': ^1.0.1

  '@platforma-sdk/test': ^1.22.84
  '@milaboratories/helpers': ^1.6.11

  '@milaboratories/software-pframes-conv': 2.1.16
  '@platforma-open/milaboratories.software-small-binaries': ^1.15.11
  '@platforma-open/milaboratories.software-mixcr': 4.7.0-147-develop	
  '@platforma-open/milaboratories.software-ptransform': ^1.3.1

  'vue': ^3.5.13
  'vue-tsc': ^2.2.8

  'zod': ~3.23.8
  'utility-types': ^3.11.0

  'typescript': ~5.5.4
  'tsup': ~8.1.2
  'turbo': ^2.4.4

  'vite': ^6.2.1
  'vitest': ^2.1.8
  '@vitejs/plugin-vue': ^5.2.1
  'rollup-plugin-sourcemaps2': ^0.5.0

  '@vueuse/core': ^12.8.2

  'ag-grid-enterprise': &ag-grid ^33.1.1
  'ag-grid-vue3': *ag-grid

  '@changesets/cli': ^2.28.1

  # other blocks used in tests

  '@platforma-open/milaboratories.samples-and-data': ^1.9.8
  '@platforma-open/milaboratories.samples-and-data.model': ^1.9.1
