packages:
  - workflow
  - model
  - ui
  - block
  - test

catalog:
  # SDK packages - exact versions, no ^ or ~
  '@milaboratories/ts-builder': 1.2.0
  '@milaboratories/ts-configs': 1.2.0
  '@platforma-sdk/workflow-tengo': 5.6.6
  '@platforma-sdk/model': 1.47.5
  '@platforma-sdk/ui-vue': 1.48.0
  '@platforma-sdk/tengo-builder': 2.4.1
  '@platforma-sdk/package-builder': 3.10.7
  '@platforma-sdk/block-tools': 2.6.27
  '@platforma-sdk/eslint-config': 1.2.0
  '@platforma-sdk/test': 1.48.1
  '@milaboratories/helpers': 1.12.0

  '@platforma-open/milaboratories.software-mixcr': 4.7.0-254-develop

  # Common dependencies - can use ^ or ~
  'vue': ^3.5.15
  'zod': ~3.23.8
  'utility-types': ^3.11.0
  'typescript': ~5.6.3
  'turbo': ^2.6.3
  'vitest': ~4.0.15
  'eslint': ^9.39.2
  '@vueuse/core': ^14.1.0

  'ag-grid-enterprise': &ag-grid ~34.1.2
  'ag-grid-vue3': *ag-grid

  '@changesets/cli': ^2.29.8
  '@zip.js/zip.js': ^2.8.11
  '@types/wicg-file-system-access': ^2023.10.7

  # other blocks used in tests
  '@platforma-open/milaboratories.samples-and-data': ^1.12.3
  '@platforma-open/milaboratories.samples-and-data.model': ^2.4.1
