packages:
  - workflow
  - model
  - ui
  - block
  - test

catalog:
  '@milaboratories/ts-builder': ^1.1.1
  '@milaboratories/ts-configs': ^1.1.0
  '@platforma-sdk/workflow-tengo': ^5.7.3
  '@platforma-sdk/model': ^1.48.14
  '@platforma-sdk/ui-vue': ^1.48.14
  '@platforma-sdk/tengo-builder': ^2.4.5
  '@platforma-sdk/package-builder': ^3.10.7
  '@platforma-sdk/block-tools': ^2.6.27
  '@platforma-sdk/eslint-config': ^1.1.0
  '@platforma-sdk/blocks-deps-updater': ^2.0.0

  '@platforma-sdk/test': ^1.48.18
  '@milaboratories/helpers': ^1.12.1

  '@platforma-open/milaboratories.software-mixcr': 4.7.0-254-develop

  'vue': ^3.5.15

  'zod': ~3.23.8
  'utility-types': ^3.11.0

  'typescript': ~5.6.3
  'turbo': ^2.5.8

  'vitest': ~4.0.16
  'eslint': ^9.38.0

  '@vueuse/core': ^13.6.0

  'ag-grid-enterprise': &ag-grid ~34.1.2
  'ag-grid-vue3': *ag-grid

  '@changesets/cli': ^2.29.7
  'js-yaml': ^4.1.0
  '@zip.js/zip.js': ^2.8.8
  '@types/wicg-file-system-access': ^2023.10.7

  # other blocks used in tests

  '@platforma-open/milaboratories.samples-and-data': ^1.10.14
  '@platforma-open/milaboratories.samples-and-data.model': ^1.11.2
