packages:
  - software/single-cell-scripts
  - software/hash-column
  - workflow
  - model
  - ui
  - block
  - test

catalog:
  '@platforma-sdk/workflow-tengo': ^4.4.2
  '@platforma-sdk/model': ^1.30.24
  '@platforma-sdk/ui-vue': ^1.30.25
  '@platforma-sdk/tengo-builder': ^2.1.3
  '@platforma-sdk/package-builder': ^2.16.0
  '@platforma-sdk/block-tools': ^2.5.47
  '@platforma-sdk/eslint-config': ^1.0.3

  '@platforma-sdk/test': ^1.30.24
  '@milaboratories/helpers': ^1.6.11

  '@platforma-open/milaboratories.runenv-python-3': ^1.1.14
  '@platforma-open/milaboratories.software-mixcr': 4.7.0-169-develop
  '@platforma-open/milaboratories.software-ptransform': ^1.4.3

  'vue': ^3.5.13
  'vue-tsc': ^2.2.10

  'zod': ~3.23.8
  'utility-types': ^3.11.0

  'typescript': ~5.5.4
  'tsup': ~8.1.2
  'turbo': ^2.5.3

  'vite': ^6.3.5
  'vitest': ~2.1.8
  '@vitejs/plugin-vue': ^5.2.3
  'rollup-plugin-sourcemaps2': ^0.5.1
  'eslint': ^9.26.0

  '@vueuse/core': ^13.1.0

  'ag-grid-enterprise': &ag-grid ^33.1.1
  'ag-grid-vue3': *ag-grid

  '@changesets/cli': ^2.29.3
  'js-yaml': ^4.1.0

  # other blocks used in tests

  '@platforma-open/milaboratories.samples-and-data': ^1.10.5
  '@platforma-open/milaboratories.samples-and-data.model': ^1.10.0
