packages:
  - workflow
  - model
  - ui
  - block
  - test

catalog:
  '@platforma-sdk/workflow-tengo': ^2.13.0
  '@platforma-sdk/model': ^1.22.59
  '@platforma-sdk/ui-vue': 1.22.39
  '@platforma-sdk/tengo-builder': ^1.17.7
  '@platforma-sdk/block-tools': ^2.5.14
  '@platforma-sdk/eslint-config': ^1.0.1

  '@platforma-sdk/test': ^1.22.59
  '@milaboratories/helpers': ^1.6.11

  '@milaboratories/software-pframes-conv': 2.1.12
  '@platforma-open/milaboratories.software-small-binaries': ^1.15.11
  '@platforma-open/milaboratories.software-mixcr': 4.7.0-133-develop

  'vue': ^3.5.13
  'vue-tsc': ^2.2.0

  'zod': ~3.23.8
  'utility-types': ^3.11.0

  'typescript': ~5.5.4
  'tsup': ~8.1.2
  'turbo': ^2.4.2

  'vite': ^6.1.1
  'vitest': ^2.1.8
  '@vitejs/plugin-vue': ^5.2.1

  '@vueuse/core': ^12.7.0

  'ag-grid-enterprise': &ag-grid ^33.1.1
  'ag-grid-vue3': *ag-grid

  '@changesets/cli': ^2.28.1

  # other blocks used in tests

  '@platforma-open/milaboratories.samples-and-data': ^1.9.8
  '@platforma-open/milaboratories.samples-and-data.model': ^1.9.1
