packages:
  - workflow
  - model
  - ui
  - block
  - test

catalog:
  '@platforma-sdk/workflow-tengo': ^4.9.3
  '@platforma-sdk/model': ^1.39.8
  '@platforma-sdk/ui-vue': ^1.39.16
  '@platforma-sdk/tengo-builder': ^2.1.12
  '@platforma-sdk/package-builder': ^2.16.0
  '@platforma-sdk/block-tools': ^2.5.68
  '@platforma-sdk/eslint-config': ^1.0.3

  '@platforma-sdk/test': ^1.39.15
  '@milaboratories/helpers': ^1.6.17

  '@platforma-open/milaboratories.software-mixcr': 4.7.0-190-develop

  'vue': ^3.5.15
  'vue-tsc': ^2.2.10

  'zod': ~3.23.8
  'utility-types': ^3.11.0

  'typescript': ~5.5.4
  'tsup': ~8.1.2
  'turbo': ^2.5.4

  'vite': ^6.3.5
  'vitest': ~2.1.9
  '@vitejs/plugin-vue': ^5.2.4
  'rollup-plugin-sourcemaps2': ^0.5.2
  'eslint': ^9.31.0

  '@vueuse/core': ^13.5.0

  'ag-grid-enterprise': &ag-grid ~33.3.2
  'ag-grid-vue3': *ag-grid

  '@changesets/cli': ^2.29.5
  'js-yaml': ^4.1.0

  # other blocks used in tests

  '@platforma-open/milaboratories.samples-and-data': ^1.10.7
  '@platforma-open/milaboratories.samples-and-data.model': ^1.10.0
