packages:
  - single-cell-scripts
  - workflow
  - model
  - ui
  - block
  - test

catalog:
  '@platforma-sdk/workflow-tengo': ^4.0.8
  '@platforma-sdk/model': ^1.29.2
  '@platforma-sdk/ui-vue': ^1.29.2
  '@platforma-sdk/tengo-builder': ^2.0.3
  "@platforma-sdk/package-builder": ^2.15.6
  '@platforma-sdk/block-tools': ^2.5.36
  '@platforma-sdk/eslint-config': ^1.0.3

  '@platforma-sdk/test': ^1.29.3
  '@milaboratories/helpers': ^1.6.11

  "@platforma-open/milaboratories.runenv-python-3": ^1.1.7
  '@platforma-open/milaboratories.software-mixcr': 4.7.0-149-develop
  '@platforma-open/milaboratories.software-ptransform': ^1.3.1

  'vue': ^3.5.13
  'vue-tsc': ^2.2.8

  'zod': ~3.23.8
  'utility-types': ^3.11.0

  'typescript': ~5.5.4
  'tsup': ~8.1.2
  'turbo': ^2.5.0

  'vite': ^6.2.6
  'vitest': ^2.1.8
  '@vitejs/plugin-vue': ^5.2.3
  'rollup-plugin-sourcemaps2': ^0.5.0
  'eslint': ^9.24.0

  '@vueuse/core': ^13.1.0

  'ag-grid-enterprise': &ag-grid ^33.1.1
  'ag-grid-vue3': *ag-grid

  '@changesets/cli': ^2.28.1

  # other blocks used in tests

  '@platforma-open/milaboratories.samples-and-data': ^1.10.4
  '@platforma-open/milaboratories.samples-and-data.model': ^1.10.0
